// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvkvpuyvmeshgcupyysj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2a3ZwdXl2bWVzaGdjdXB5eXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzOTc0MTAsImV4cCI6MjA4Njk3MzQxMH0.CEPuwvWzaA_nOL_ePnHbuY2me-N28oBAxaIEZBoFtQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});